export { default as Admin } from './Admin'
export { default as AdminRoutes } from './AdminRoutes'
export * from './Anamnesis'
export * from './Appointments'
export * from './Doctors'
export * from './GOH'
export * from './Patients'
export * from './Persons'
export * from './PersonsRoles'
export * from './PhysicalExaminations'
export * from './Roles'
export * from './Specialties'
export * from './Users'
